In [1]:
import numpy as np

# Reward Table for 9 State-Action pair

In [2]:
reward_table=([[0,1,0,0,0,0,0,0,0],[1,0,1,0,0,0,0,0,0],[0,1,0,0,0,1,0,0,0],[0,0,0,0,0,0,1,0,0],[0,1,0,0,0,0,0,1,0],[0,0,1,0,0,0,0,0,0],[0,0,0,1,0,0,0,1,0],[0,0,0,0,1,0,1,0,1],[0,0,0,0,0,0,0,1,0]])

In [3]:
reward_table=np.array(reward_table)

In [4]:
reward_table

array([[0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [5]:
# reward_table
# for i in range(9):
#     for j in range(9):
#         if reward_table[i][j]!=1:
#             reward_table[i][j]=-1
#         elif reward_table[i][j]==1:
#             reward_table[i][j]=(i+j)*100
# print(reward_table)            
            

# Initialization of Q-matrix

In [6]:
Q= np.matrix(np.zeros([9,9]))

In [7]:
Q

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
gamma=0.8

In [9]:
initial_state=1

# List of all possible actions given any current state

In [10]:
def playable_actions(state):
    aval_action=[]
    current_row_of_state=reward_table[state,]
    x=np.where(current_row_of_state>0)
    aval_action.append(x)
    aval_action=np.array(aval_action)
    value=aval_action[0][0]
    return value

In [11]:
playable_actions(5)   # indexing start from 0 hence 0 to 8 are possible values for state and action

array([2], dtype=int64)

# Randomly selecting one action from all possible action

In [12]:
def choosing_next_action(available_actions_possible):
    
    next_action=int(np.random.choice(available_actions_possible,1))
    return next_action
    

In [13]:
choosing_next_action(playable_actions(1))

0

In [14]:
gamma=0.8
alpha=0.9
end_state=5

# Updating Q value 

In [15]:
def update(current_state,action,gamma,alpha,end_state):
    rewards_new=np.copy(reward_table)
    rewards_new[end_state,end_state]=100000
    Temporal_difference=rewards_new[current_state,action]+gamma*Q[action,np.argmax(Q[action,])]-Q[current_state,action]
    Q[current_state,action]+=alpha*Temporal_difference
    
    

#  Training Q matrix

In [16]:
for i in range(100000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    available_actions=playable_actions(current_state)
    action=choosing_next_action(available_actions)
    update(current_state,action,gamma,alpha,end_state)

# Updated Q matrix

In [17]:
print("............Trained Q-Matrix(Normalized)....................")
print(Q/np.max(Q)*100)

............Trained Q-Matrix(Normalized)....................
[[  0. 100.   0.   0.   0.   0.   0.   0.   0.]
 [100.   0. 100.   0.   0.   0.   0.   0.   0.]
 [  0. 100.   0.   0.   0. 100.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 100.   0.   0.]
 [  0. 100.   0.   0.   0.   0.   0. 100.   0.]
 [  0.   0. 100.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 100.   0.   0.   0. 100.   0.]
 [  0.   0.   0.   0. 100.   0. 100.   0. 100.]
 [  0.   0.   0.   0.   0.   0.   0. 100.   0.]]


In [18]:
# Testing 
# let say our goal state is 5


#    Testing for given current and end state

In [ ]:
current_state=2
end_state=8
steps=[current_state]
while current_state!=end_state:
    next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index=int(np.random.choice(next_step_index,size=1))
    else:
        next_step_index=int(next_step_index)
    steps.append(next_step_index) 
    current_state=next_step_index


# Desired path

In [ ]:
print(steps)